### ISSUE TITLE
Is this still active?

### ISSUE THREAD

**Issue by marcoscaceres** [WICG/sw-launch#22]
Hey folks, is this alive? Could this be moved to the SW Working Group as a feature request?

**Comment by mgiuca** [comment]
Hi Marcos,

Hasn't had a lot of attention, but I would like to see it go ahead. Having it be a FR on the SW WG sounds good. The reason we put it in WICG is that its scope felt like a bigger project than just a single feature request. I'm open to moving it.

**Comment by LuHuangMSFT** [comment]
Hi @marcoscaceres. I completely missed this. I have updates for the issues here that I will post today or tomorrow.
We have been actively designing and prototying changes for the explainer here but I haven't done a good job of being responsive here. 

Hi @mgiuca. We have some ideas to share with you for integrating with declarative link capturing. I'll reach out over e-mail.

**Comment by LuHuangMSFT** [comment]
Hi @mgiuca. There are some ideas I was hoping to share with you on integrating with declarative link capturing. I'll reach out over e-mail.

**Comment by LuHuangMSFT** [comment]
Sorry Marcos if you got an email notification. My comment didn't make sense because I thought I was in a different repo. Deleted.

**Comment by marcoscaceres** [comment]
heh, no problem. I constantly post comments to the wrong repo :)

**Comment by alancutter** [comment]
Has been in active development for the past several months.
