### ISSUE TITLE
What is that actual impact of this

### ISSUE THREAD

**Issue by TomCJones** [WICG/sw-launch#27]
I was asked to evaluate this and came up with these from the explainer - was i correct?

This is an attempt to get software launch to work, even tho that proposal has been around for several years without getting implementations.

Explainer seems to be mostly about when to create a new browser tab when a link in the existing PWA is clicked.
Combined with the above this would work from native apps as well.
Would also work from file handler as well.
It appears that the "launcher" only knows how to create new tabs and this would fix that.

**Comment by alancutter** [comment]
This might make more sense in the context of declarative link capturing. See the different capture_links behaviours listed in this explainer: https://github.com/WICG/sw-launch/blob/main/declarative_link_capturing.md#proposal
The SW launch event is for when you need more fine grained control than what the declarative options provide.
