### ISSUE TITLE
I tried the Chrome Origin Trial "Declarative Link Capturing", didn't work, is there a live working demo?

### ISSUE THREAD

**Issue by ZYinMD** [WICG/sw-launch#29]
I'm trying to enable this feature for my PWA, here's what I did:
1. Sign up for the Chrome Origin Trial "Declarative Link Capturing" at 
https://developer.chrome.com/origintrials/#/register_trial/4285175045443026945
1. Got a token.
1. Put the token in a meta tag: `<meta http-equiv="origin-trial" content="my_token" />` in the index.html of my PWA.
1. Add a field in manifest:  `"capture_links": "existing-client-navigate",`
1. Deploy
1. Visit my PWA using Chrome v91 or v92 (I used Chrome Beta and Canary).
1. Install the PWA.
1. Restart Chrome, and visit the url of my PWA again.

At this point, I expect the url to be launched via my installed PWA, not in a tab. However, nothing seems to have changed - the url is still opened in a tab.

Did I misunderstand the trial? If not, is there a live demo of a PWA that has implemented this trial so I can visit it and experience it?

**Comment by alancutter** [comment]
Sorry for the confusion, we don't support "existing-client-event" yet. I'll have the origin trial description updated to reflect this.
Here is an example site using the origin trial: https://hill-glitter-tree.glitch.me/

**Comment by ZYinMD** [comment]
Thanks, I'm still confused about your answer. Do you mean I'll need to both enable the trial and enable the chrome flag to make it work?
