### ISSUE TITLE
Should apps that aren't installed have launch events triggered?

### ISSUE THREAD

**Issue by fallaciousreasoning** [WICG/sw-launch#3]

**Comment by raymeskhoury** [comment]
I thought about this a bit and I think that we should start with the answer being "no". I think that clicking on links that trigger things like a delay before the app starts or just a notification or even jumping to a different tab will violate user's expectations of the web. 

Further, launch event handlers can behave badly. It's harder to attribute bad behavior to sites that aren't installed vs sites that are installed.

**Comment by fallaciousreasoning** [comment]
I tend to agree with you. I'll add a section to the explainer with our rationale.

**Comment by fallaciousreasoning** [comment]
Interesting midway opinion: Maybe we should trigger launch events for stuff like registerProtocolHandler, fileHandlers, shortcut launches and the like, just not navigation launch events? This seems like more of a SHOULD/CAN recommendation anyway, where user agents can decide for themselves what they want to do.

**Comment by raymeskhoury** [comment]
I think we might end up with the same problems I described above. But I totally agree with the restriction being a recommendation rather than mandated.

**Comment by fallaciousreasoning** [comment]
Cool :)
