### ISSUE TITLE
unsupported extensions ?

### ISSUE THREAD

**Issue by sigurdle** [WICG/sw-launch#38]
I'm trying out this API, I'm finding that:

1) If there are duplicate extension entries then no file handlers will be registered
2) If the following extensions are attempted at being registered: exe, fon, scr, ttf (and maybe more), then no file handlers will be registered

This is found out through debugging, if this is correct (?), then document this in the spec (or maybe this is a limitation of Windows ?)

(also, I'm trying this out in Edge, since its easier to uninstall/install a wpa)

**Comment by alancutter** [comment]
This sounds like something to file in crbug.com rather than as a spec issue.
Aside: This is the launch_handler spec repo, for file_handlers spec issues you'd create an issue in: https://github.com/WICG/manifest-incubations/issues/
