### ISSUE TITLE
Should launch events be triggered by `window.open`?

### ISSUE THREAD

**Issue by fallaciousreasoning** [WICG/sw-launch#4]
Intuitively, it feels like they should be (e.g. by a site adding `window.open('yourapp.com')` to its button's click handler). 

However, it may be difficult to reconcile asynchronous launch events with the synchronous `window.open` API. Hopefully we can find some way around this issue, or it will somewhat limit the usefulness of launch events.

**Comment by raymeskhoury** [comment]
One way forward here would be to open the popup/tab and if it triggers a launch event, to then close it again. We might not have a ton of choice because the navigation in the window will only happen after window.open has finished

**Comment by fallaciousreasoning** [comment]
Interesting. I think I'd be comfortable with a V0 of launch events that doesn't work at all with window.open

**Comment by raymeskhoury** [comment]
I agree, we might just want to think through it a bit.

**Comment by raymeskhoury** [comment]
Notes added to the explainer.
