### ISSUE TITLE
Deprecate the old launch explainer and fix up the top-level README

### ISSUE THREAD

**Issue by mgiuca** [WICG/sw-launch#42]
(Based on some confusion within Google about what the current plans were.)

The top-level README file only links to the old sw-launch explainer. Our plans have now shifted, with declarative-link-capturing being proposed as a simpler cousin spec to sw-launch, and then launch-handler subsuming both of those.

The sw-launch and declarative-link-capturing explainers should now be considered deprecated. launch-handler will eventually include service worker launch event, but only for use cases that don't fit the foreground page handling. Those two explainers should be marked obsolete, and the top-level README file should link to launch-handler primarily, and the others as historical artifacts. Updating the list of authors would also be good.

**Comment by alancutter** [comment]
Fixed by: https://github.com/WICG/sw-launch/pull/49
