### ISSUE TITLE
Consider removing navigate_existing_client

### ISSUE THREAD

**Issue by kenchris** [WICG/sw-launch#45]
In response to https://github.com/w3ctag/design-reviews/issues/683

Is navigate_existing_client expected to received more values in the future (beyond always and never).

If not, couldn't we do "route_to": "existing-client-replace" or similar?

This just feels like one additional option for one specific routing option

**Comment by alancutter** [comment]
navigate_existing_client is quite awkward naming and semantics wise. I'm quite open to considering other options.

It is open to receiving more options in the future (e.g. URL filtering) but I can't think of a solid use case to justify any such extensions.

Would your suggestion be something like `"route_to": "new-client" | "existing-client-replace" | "existing-client-retain" | "service-worker"`?

**Comment by kenchris** [comment]
Yes, that was my indention. I think the meaning is pretty clear for developers this way and non indirectly implied.

**Comment by alancutter** [comment]
SGTM.

**Comment by tomayac** [comment]
+1, I had similar feelings when working on the (in-progress) article (https://github.com/GoogleChrome/web.dev/pull/6908).
