### ISSUE TITLE
Consolidate the launch_handler API with MiniApps

### ISSUE THREAD

**Issue by alancutter** [WICG/sw-launch#52]
Extracted from TAG review: https://github.com/w3ctag/design-reviews/issues/683#issuecomment-1048422406
@maxpassion, @QingAn

MiniApps define their own application lifecycle: https://w3c.github.io/miniapp-lifecycle/#miniapp-global-application-lifecycle
We should attempt to be compatible with the MiniApp model and any APIs they've already established.

**Comment by alancutter** [comment]
I don't quite understand https://w3c.github.io/miniapp-lifecycle/#dom-globallaunchedcallback which appears relatively similar to [LaunchQueue](https://github.com/WICG/sw-launch/blob/main/launch_handler.md#launchqueue-and-launchparams-interfaces). 

When is this set and how does that happen prior to the MiniApp getting launched?

Do MiniApps have multiple ways of being launched that ought to be intercepted by already running instances e.g. share targets or link captures? Is `globalLaunchedCallback` the way to intercept them?

**Comment by alancutter** [comment]
@QingAn do mini apps have the concept of being open multiple times in separate windows/tabs? Do they exist on desktop environments?

**Comment by tomayac** [comment]
Mini apps on desktop are [very much a thing](https://web.dev/mini-app-alternative-runtime-environments/#mini-apps-on-the-desktop). As far as my experiments go, there can always only be one instance of a mini app at any given time.

**Comment by alancutter** [comment]
Fantastic article, thank you!

**Comment by alancutter** [comment]
Do mini apps even have their own window or do they live purely in the context of the super app? I suppose it's possible for super apps to behave like browsers and have separate windows/tabs for each mini app if they wanted to...

**Comment by tomayac** [comment]
Mini apps launch in stand-alone windows. Here's an example from a WeChat mini app on desktop:

<img width="1136" alt="Screen Shot 2022-04-21 at 09 27 01" src="https://user-images.githubusercontent.com/145676/164400345-5af107bf-31e1-487b-b980-ce0205737151.png">

The [360 Browser](https://web.dev/mini-app-alternative-runtime-environments/#mini-apps-in-the-360-secure-browser) is both a regular browser and a mini app host. Mini apps launched from the browser have access to non-Web APIs, and launch in separate windows.

**Comment by alancutter** [comment]
Given that MiniApps can only run one window at a time I believe `launch_handler` will pretty much be ignored by the user agent just like on mobile where the window semantics are similar.
