### ISSUE TITLE
Behavior of existing-client-* options when there are no existing clients

### ISSUE THREAD

**Issue by LuHuangMSFT** [WICG/sw-launch#54]
How would `existing-client-navigate` and `existing-client-retain` behave when no existing clients are found? 

* `existing-client-navigate`: same behavior as `new-client`? 
* `existing-client-retain`: should this a.) open new client and navigate, or b.) open new client and add `LaunchParams` to `LaunchQueue`?

**Comment by alancutter** [comment]
For either option it behaves as new-client if there are no clients available.

One possible extension the explainer mentions is a "new_client_url" should web apps not want to actually navigate to the target URL in the common case.
