### ISSUE TITLE
"existing-client-retain" does not work but "existing-client" does

### ISSUE THREAD

**Issue by giraffepoo** [WICG/sw-launch#55]
![musicrerror](https://user-images.githubusercontent.com/31707712/161117592-83860f7c-bf1d-4ecc-84d6-6609d1c9411a.png)

The current demo app under https://web.dev/launch-handler/ does not work as the error above is shown. I looked through chromium bugs list to find that[ "existing-client" works](https://bugs.chromium.org/p/chromium/issues/detail?id=1305904) and I confirmed it with my browser. 

Is there going to be a release soon for "existing-client-retain"? (Sorry I'm very new to PWA feature dev - asking as this is a feature I heavily need for current project)

**Comment by alancutter** [comment]
The implementation is coming, in the meantime use both for backwards compat:
```js
"launch_hander": {
  "route_to": ["existing-client-retain", "existing-client"],
  "navigate_existing_client": "never"
}
```

**Comment by alancutter** [comment]
Old browsers will ignore any unknown enum values in the "route_to" list until they find one they can parse.

**Comment by alancutter** [comment]
Ty for typo spotting.

There was no navigate_new_clients field, only navigate_existing_client. New clients always navigate otherwise they'd be about:blank.
