### ISSUE TITLE
Respec errors

### ISSUE THREAD

**Issue by yoavweiss** [WICG/sw-launch#66]
You probably want to change the status to "CG draft"

**Comment by alancutter** [comment]
Hmm, it's still unhappy with that:
```
W3C Working Group documents can't use "CG-DRAFT" for the [specStatus](https://respec.org/docs/#specStatus) configuration option.
How to fix: Pleas see [specStatus](https://respec.org/docs/#specStatus) for appropriate status for W3C Working Group documents.
```

Maybe ED or WD instead?

**Comment by yoavweiss** [comment]
"group" should be "WICG", most probably

**Comment by alancutter** [comment]
I think this belong in the webapps group. Just cargo culting off some of the other specs in that group (https://www.w3.org/groups/wg/webapps/publications) it seems ED is what this file ought to be set to.

**Comment by yoavweiss** [comment]
Is there consensus in webapps to adopt this? If so, we should transfer the repo there. If not, this should be a CG draft in the WICG.

**Comment by alancutter** [comment]
The github repo location detail eluded me, thanks for catching that.
